name: Linting and Unit Tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.1.0
      with:
        node-version: 12.x
    - name: Cache node modules
      uses: actions/cache@v3.0.1
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: npm i
    - run: npm run lint
    - run: npm run test:unit

  test-compute-at-edge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.1.0
    - name: Set up Fastly CLI
      uses: fastly/compute-actions/setup@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: npm i
    - run: npm run build
    - run: npm i
      working-directory: fastly/c-at-e
    - run: npm run lint
      working-directory: fastly/c-at-e
    - run: npm run test
      working-directory: fastly/c-at-e
